Repository fredysomy/pysonDB, pull requests merged in 2021-10, with the labels that each got.

#44 Replaced fire with Argparse
  docs/cli.md
  pysondb/cli.py
  requirements.txt
  setup.py
Labels: hacktoberfest, hacktoberfest-accepted

#46 remove imageutils
  README.md
  docs/add.md
  docs/cli.md
  docs/delete.md
  docs/get.md
  docs/image_utils.md
  docs/re_search.md
  docs/update.md
  pysondb/imageutils/__init__.py
  pysondb/imageutils/imageutils.py
Labels: hacktoberfest, hacktoberfest-accepted

#47 Fix .find bug
  pysondb/db.py
  tests/tests_json_database.py
  tests/tests_json_uuid_database.py
  tests/tests_yaml_database.py
  tests/tests_yaml_uuid_database.py
Labels: hacktoberfest

#49 Optimised addMany method of JsonDatabase
  CHANGELOG.md
  pysondb/db.py
  setup.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#56 error handling when displaying database and database is null
  CHANGELOG.md
  pysondb/cli.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#57 error handling when converting to csv database and database is null
  CHANGELOG.md
  pysondb/cli.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest
